server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.hipudding.cn:3306/peccancy?characterEncoding=utf8&useSSL=false
    username: root
    password: test@1234
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database : MYSQL
    properties:  
      hibernate:  
        dialect : org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        
  thymeleaf:
      cache: false
      mode: LEGACYHTML5
      
  http:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
        
  resources:
    static-locations: classpath:/static/,classpath:/templates/,file:${img_path}
    
logging:
  level: info
  file: ${log_path}/peccancy.log
  root: INFO

token_expire: 7200
token_url: https://api.weixin.qq.com/cgi-bin/token
my_token: hipudding
app_id: wxcab1dccd3a31b5eb
app_secret: 536cf5ea9aa8c0117b1919eee28cefa7
img_path: /Users/huafengchun/Pictures/test
log_path: /Users/huafengchun/Pictures/test