server:
  port: 443
  ssl:
    key-store: ${key_path}/keystore.p12
    key-store-password: hipudding
    keyStoreType: PKCS12
    keyAlias: tomcat
    
security:
  require-ssl: true
  

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.hipudding.cn:3306/peccancy?characterEncoding=utf8&useSSL=false
    username: root
    password: test@1234
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database : MYSQL
    properties:  
      hibernate:  
        dialect : org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        
  thymeleaf:
      cache: false
      mode: LEGACYHTML5
      
  http:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
        
  resources:
    static-locations: classpath:/static/,classpath:/templates/,file:${img_path}
    
logging:
  level: info
  file: ${log_path}/peccancy.log
  root: INFO


my_token: hipudding
img_path: /var/peccancy/image
log_path: /var/peccancy/log
key_path: /var/peccancy/key
